name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: docker

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file customedockerfile --tag jalen1123/docker-images:latest

    - name: log in to docker hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.dockerhub_username }}
        password: ${{ secrets.dockerhub_passwd }}
    
    - name: push docker image
      run: docker push ${{ secrets.dockerhub_username }}/docker-images:latest